### PR TITLE
allow to choose the default license

### PR DESCRIPTION
**Pull request by christophehurpeau**
Add an option to select the default license

### CODE REVIEW

**Comment by christophehurpeau** [comment]
Any reason for not merging this ?

**Comment by jozefizso** [comment]
I haven't had time to maintain this project.

I will take a look at your newer pull request with yeoman-generator 1.0

**Comment by SBoudrias** [comment]
@jozefizso hey, we're relying on this generator from many official Yeoman generators, I'd be glad to land a hand maintaining it if you so wish.

**Comment by jozefizso** [comment]
@SBoudrias sure, you can maintain it. I would we glad, as it is just side project for me.

**Comment by SBoudrias** [comment]
@jozefizso you'd just need to add me as a contributor and give me access to the package on npm.

**Comment by jozefizso** [comment]
@SBoudrias Done.

**Pull request merged**
