### PR TITLE
Add more licenses

### LINKED ISSUE #12: Add GPL-3.0 support
Please add support for the [GPLv3](http://www.gnu.org/licenses/gpl-3.0.en.html)

### LINKED ISSUE #13: Add AGPL-3.0 support
Add support for [AGPLv3](http://www.gnu.org/licenses/agpl-3.0.en.html)

### PR DESCRIPTION
**Pull request by amingilani**
This does more than fix #12 and fix #13

Adds the license files:
1. GPL3
2. GPL2
3. LGPL2
4. LGPL3
5. AGPL3
6. WTFPL

I have not written the tests though, since I have a day job, and I thought quickly fixing this would be nice, but I encourage someone to write them? Pretty please? Also, these are untested.

### CODE REVIEW

**Comment by hbetts** [comment]
:+1:

**Comment by jozefizso** [comment]
Please, include tests for new licenses.

**Comment by canercandan** [comment]
:+1:

**Comment by SBoudrias** [comment]
Are all these licenses very common? I feel we should probably limit the choices to well known common licenses. I wouldn't want the end user to be overwhelm by a tons of choices.

**Comment by hbetts** [comment]
So a few issues here. First, multiple versions of a license. Should only the latest iteration of a license be supported? Second, if limiting the total number of licenses, should a _custom_ license option be provided that allows the user to input license information?

**Comment by SBoudrias** [comment]
> Second, if limiting the total number of licenses, should a custom license option be provided that allows the user to input license information?

It'd be possible to add a "more" option and then show an extensive list of licenses.

**Comment by iamstarkov** [comment]
I would rather create new `generator-license-extended` based on current one. This generator will be simple as it is now. Someone who needs more licenses to choose from, will use new extended generator. what do you think?

**Comment by ek9** [comment]
- GNU GPL 3.0 added in PR #43 
- GNU AGPL 3.0 added in PR #42   
- MPL 2.0 (Mozilla Public License) - #44 

Otherwise, I decided to comment regarding other licenses:

Regarding 2.0 versions of `GPL`/`LGPL`: I don't believe they are necessary as any new projects are more recommended to be started with 3.0 or later version. This is even included in the updated licenses as they state themselves, that user can choose to use newer version at their own discretion.

`WTFPL`, while can be considered a form of licensing, it isn't really used often (or in a serious matter), so I wouldn't say it adds much having it in the generator.

This leaves with `LGPL 3.0`, which I believe might be useful to add.

This would make most popular and open-source approved licenses available in the generator.

**Comment by ek9** [comment]
I've made a separate issue so it's possible to discuss it (and it's likely where it can be found by others). As a lot of the licenses were already merged, I'd suggest to close this PR.

**Comment by millette** [comment]
@ek9 is referring to #45

**Pull request closed without merging**
