### PR TITLE
Store prompt answer

### PR DESCRIPTION
**Pull request by kievechua**
Store all prompt answers in Yeoman config.
So other author can reuse the field.

### CODE REVIEW

**Comment by SBoudrias** [comment]
This won't really allow you to read what the answer to the question was from outside generator-license.

Instead, you should read the value inside `package.json`

**Comment by kievechua** [comment]
I though I can get the .yo-rc.json.
Only realise it won't write only it finish.
Scrap that.

Thank for reply, guess have to write basic generator class and extend it instead.

**Comment by SBoudrias** [comment]
@kievechua why not read it from `package.json`? This generator will updated the field with the correct value.

**Comment by kievechua** [comment]
@SBoudrias That feature is what I'm trying to do, should read through the code.
Basically building first generator to scaffold an empty project (no package.json), so come upon this project. Then though trying to be clever so user don't need to type twice for name, email and etc.

I think my own code override the package.json created, that's why I didn't see it.
Still learning the best practise and how other build it.

thanks again.

**Comment by SBoudrias** [comment]
@kievechua you can ask these questions in your generator, then pass them as option to generator-license.

**Comment by kievechua** [comment]
Yes, planning to do that.
Just searching around to see if anyone have a GeneratorStarter asking those question.
So I can just extend it instead.

**Comment by ek9** [comment]
@kievechua you can have a look at https://github.com/ek9/generator-licensor as an example. It uses this and generator-license-cc to create licenses. Perhaps that will help you writing your own generator.

**Pull request closed without merging**
